### ISSUE TITLE
tang-gen: endless loop if dbdir doesn't exist or no write access

### ISSUE THREAD

**Issue by frasertweedale** [npmccallum/tang#1]
This do-while in tang-gen.c is problematic.  I'm not sure why loop is needed but
either existance/`access` checks are needed or, as a last resort, bail out after
a set number of loops.

Happy to patch this myself but needed to find out why the do-while is there
first :)

    } else {
        do {
            r = keyfilegen(dbdir, filename);
            if (r != 0)
                error(EXIT_FAILURE, r, "Error generating keyfile name");

            file = fopen(filename, "wx");
        } while (!file);
    }

**Comment by npmccallum** [comment]
The loop is there to catch random name collisions (unlikely, but a possibility). keyfilegen() creates a random filename and fopen(filename, "wx") creates the file with that name. If it fails, it may indicate a name collision. Maybe something like:
    while (!file && errno == EEXIST)
